DROP TABLE userDateExerciseJoins;
DROP TABLE weightUserJoins;
DROP TABLE cardioExerciseDateJoins;
DROP TABLE calisthenicExerciseDateJoins;
DROP TABLE setExerciseDateJoins;
DROP TABLE bodyPartExerciseJoins;
DROP TABLE exerciseDateJoins;
DROP TABLE dateUserWorkoutJoins;
DROP TABLE bodyParts;
DROP TABLE setWeights;
DROP TABLE cardioSets;
DROP TABLE calisthenicSets;
DROP TABLE exercises;
DROP TABLE workoutNames;
DROP TABLE datetimes;
DROP TABLE weightUserJoins;
DROP TABLE weights;
DROP TABLE users;

