-- DROP TABLE setExerciseDateJoins;
-- DROP TABLE exerciseDateJoins;
-- DROP TABLE dateUserWorkoutJoins;
-- DROP TABLE setWeights;
DROP TABLE exercises;
DROP TABLE workoutNames;
DROP TABLE datetimes;
DROP TABLE users;
-- DROP TABLE weights;
-- DROP TABLE weightUserJoins;
